Save user response to report form on Datastore
googleinterns/step202-2020 pull request #14
Opened 2020-06-30 05:37 UTC by jiminbyun

Closes #1 
It reads the form and save it to datastore as report, which has following attributes: title, longitude, latitude, timestamp, incidentType, description. Map was used between parameter name and html id, and between parameter name and default value because first there are a lot of fields, and also it will be easier to add extra field for images. Also, instead of using button type as submit for submit button, I used regular button that fetches with method POST on click to avoid reloading the whole page. 

Currently not reading location field in user input because it will be prepopulated later.

2020-06-30 06:12 UTC, AshleyLTW approved these changes

2020-06-30 06:12 UTC, AshleyLTW commented on web-app/src/main/java/com/google/sps/data/Report.java
> +  /** TODO (Ashley): Add image. */
nit: AshleyLTW?

2020-06-30 06:12 UTC, AshleyLTW commented on web-app/src/main/java/com/google/sps/servlets/ReportServlet.java
> +/** Servlet that returns some example content. TODO: modify this file to handle comments data */
Should probably change this from the walkthrough comment

2020-07-01 02:01 UTC, darrnshn requested changes
Looks good, but hoping we can have some tests too!

2020-07-01 02:01 UTC, darrnshn commented on web-app/src/main/webapp/index.html
> +            <button class="u-full-width" type="button"
do you need to put `type="button"` if it's already a button?

2020-07-01 02:01 UTC, darrnshn commented on web-app/src/main/webapp/script.js
> +  let searchParams = new URLSearchParams();
nit: const?

2020-07-01 02:01 UTC, darrnshn commented on web-app/src/main/webapp/script.js
> +  const URLQuery = reportFormToURLQuery();
nit: naming should be `urlQuery`?

2020-07-01 02:01 UTC, darrnshn commented on web-app/src/main/java/com/google/sps/servlets/ReportServlet.java
> +    for (String paramName : PARAM_DEFAULT_MAP.keySet()) {
could we add some simple tests?

2020-07-07 06:40 UTC, darrnshn approved these changes

2020-07-07 06:40 UTC, darrnshn commented on web-app/src/main/java/com/google/sps/servlets/ReportServlet.java
> +
nit: remove blank line?

2020-07-07 06:40 UTC, darrnshn commented on web-app/src/test/java/com/google/sps/servlets/ReportServletTest.java
> +    Double latitude = 1.11;
nit: you can probably just inline these into the test expectations

2020-07-07 06:40 UTC, darrnshn commented on web-app/src/test/java/com/google/sps/servlets/ReportServletTest.java
> +  public void testReportServlet() throws IOException {
nit: maybe a test with invalid parameters,and check that we get an exception?

2020-07-07 07:16 UTC, merged