Tests work with new Report class
googleinterns/step202-2020 pull request #47
Opened 2020-07-09 06:27 UTC by AshleyLTW

Modify our code so that it checks if an image exists before calling getUploadUrl, allowing us to test createReportEntity without having to mock blobstore. 

I also modified how the timestamp is parsed (parse instead of hardcoding an epoch time) so the test passes across timezones.

2020-07-09 23:32 UTC, jiminbyun approved these changes

2020-07-10 03:05 UTC, darrnshn requested changes

2020-07-10 03:05 UTC, darrnshn commented on web-app/src/test/java/com/google/sps/servlets/ReportServletTest.java
> +    Assert.assertEquals(testReport.getProperty("timestamp"), epochTime);
I would just create the Date manually instead of parsing, and make the timeStampFormatter private again

2020-07-13 02:02 UTC, darrnshn approved these changes

2020-07-13 02:12 UTC, merged