More unit tests for filtering
googleinterns/step202-2020 pull request #62
Opened 2020-07-20 23:15 UTC by jiminbyun

Unit test each for filtering timeframe and categories

2020-07-20 23:51 UTC, AshleyLTW approved these changes

2020-07-23 02:27 UTC, darrnshn requested changes

2020-07-23 02:27 UTC, darrnshn commented on web-app/src/main/webapp/jasmine/spec/loadDataSpec.js
> +  const sampleDataOld = [
please put the actual test code inside the `it` to make it clear what each test is actually testing. Note that your tests should work correctly regardless of the order they're run.

2020-07-24 01:58 UTC, darrnshn approved these changes

2020-07-26 23:26 UTC, merged